config/routes.rb
People::Application.routes.draw do

  resources :professors
  resources :courses
  resources :emails

  root :to => "Professors#description", :defaults => { :format => :xml}
  match "adminprof" => "Professors#index"
  match "admincourses" => "Courses#index"
  match "adminemails" => "Emails#index"
  match "index" => "Professors#description", :defaults => { :format => :xml}
  match "status" => "Professors#status", :defaults => { :format => :xml}
  match "metainfo" => "Professors#meta_info", :defaults => { :format => :xml}
  match "people" => "Professors#list", :defaults => { :format => :xml}
  match "people/:id" => "Professors#specific", :defaults => { :format => :xml}
  match "search" => "Professors#search", :defaults => { :format => :xml}
  match "specsearch" => "Professors#specificsearch", :defaults => {:format => :xml}
  match "recommendation" => "Professors#recommendation", :defaults => { :format => :xml}

end

app/models/professor.rb
class Professor < ActiveRecord::Base
  has_many :emails
  has_many :courses
end

app/controllers/professors_controller.rb
class ProfessorsController < ApplicationController
  # GET /professors
  # GET /professors.xml

  def description
    @address = get_address
    respond_to :xml
  end

  def meta_info
    @address = get_address
    respond_to :xml
  end

  def status
    respond_to :xml
  end

  def list
    @address = get_address
    @start = (params[:start] || '1').to_i
    @end = (params[:end] || '20').to_i
    @next = @address+"/people?start="+(@end+1).to_s+"&end="+(@end+1+@end-@start).to_s

    @professors = Professor.find(:all, :order => "professor_name", :offset => @start-1, :limit => @end+1-@start.to_i)

    if @professors.count != @end+1-@start then
      @next = ""
    else
      if @professors[@end-@start].professor_name == Professor.order(:professor_name).last.professor_name
        @next = ""
      end
    end

    respond_to :xml
  end

  def specific
    @professor = Professor.find(params[:id])
    prof_id = @professor.professor_id
    @emails = Email.where(:professor_id => prof_id)
    @courses = Course.where(:professor_id => prof_id)

    respond_to :xml
  end

  def search

    @address = get_address
    @keyword =  params[:keyword].gsub("%", "\%").gsub("_", "\_")
    @start = (params[:start] || '1').to_i
    @end = (params[:end] || '20').to_i
    @next = @address+"/search?keyword="+@keyword+"&start="+(@end+1).to_s+"&end="+(@end+1+@end-@start).to_s
    keyarray = @keyword.to_s.split(' ')
    professors = Professor.find(:all, :order => :professor_name, :conditions=> ["professor_name like ?","%"+@keyword+"%"])

    @list = []
    counter = 1
    professors.each do |p|

      if counter >= @start then
           @list << p
      end

      counter = counter.to_i+1

      if counter > @end then
        break
      end

    end

    if counter<=@end then
      @next = ""
    elsif professors[@end-@start].professor_name == Professor.find(:all, :order => :professor_name, :conditions=> ["professor_name like ?","%"+@keyword+"%"]).last.professor_name
      @next = ""
    end

    respond_to :xml
  end

  def recommendation

    @keyword = params[:keyword].gsub("%", "\%").gsub("_", "\_")
    @start = params[:start] || '1'
    @end = params[:end] || '10'
    @next = @end.to_i+1
    professors = Professor.find(:all, :conditions=> ["professor_name like ?", @keyword + "%"], :offset => @start.to_i-1, :limit => @end.to_i+1-@start.to_i)

    if professors.count != 10 then
      @next = ""
    end

    @list = []
    professors.each do |professor|
      @list << professor.professor_name
    end

    respond_to :xml
  end

  def index
    @professors = Professor.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @professors }
    end
  end

  # GET /professors/1
  # GET /professors/1.xml
  def show
    @professor = Professor.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @professor }
    end
  end

  # GET /professors/new
  # GET /professors/new.xml
  def new
    @professor = Professor.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @professor }
    end
  end

  # GET /professors/1/edit
  def edit
    @professor = Professor.find(params[:id])
  end

  # POST /professors
  # POST /professors.xml
  def create
    @professor = Professor.new(params[:professor])

    respond_to do |format|
      if @professor.save
        format.html { redirect_to(@professor, :notice => 'Professor was successfully created.') }
        format.xml  { render :xml => @professor, :status => :created, :location => @professor }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @professor.errors, :status => :unprocessable_entity }
      end
    end
  end


  # PUT /professors/1
  # PUT /professors/1.xml
  def update
    @professor = Professor.find(params[:id])

    respond_to do |format|
      if @professor.update_attributes(params[:professor])
        format.html { redirect_to(@professor, :notice => 'Professor was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @professor.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /professors/1
  # DELETE /professors/1.xml
  def destroy
    @professor = Professor.find(params[:id])
    @professor.destroy

    respond_to do |format|
      format.html { redirect_to(professors_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/professors_helper.rb
module ProfessorsHelper
end

app/views/professors/_form.html.erb
<%= form_for(@professor) do |f| %>
  <% if @professor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@professor.errors.count, "error") %> prohibited this professor from being saved:</h2>

      <ul>
      <% @professor.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :professor_id %><br />
    <%= f.text_field :professor_id %>
  </div>
  <div class="field">
    <%= f.label :professor_name %><br />
    <%= f.text_field :professor_name %>
  </div>
  <div class="field">
    <%= f.label :sector %><br />
    <%= f.text_field :sector %>
  </div>
  <div class="field">
    <%= f.label :category %><br />
    <%= f.text_field :category %>
  </div>
  <div class="field">
    <%= f.label :room %><br />
    <%= f.text_field :room %>
  </div>
  <div class="field">
    <%= f.label :building %><br />
    <%= f.text_field :building %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/professors/description.xml.erb
<record title="Serviço sobre Pessoas">
  <text>Este serviço fornece informação detalhada sobre todos os docentes da FCT</text>
  <link href='<%=$myApplicationURL%>/people'>Lista de Professores</link>
</record>

app/views/professors/edit.html.erb
<h1>Editing professor</h1>

<%= render 'form' %>

<%= link_to 'Show', @professor %> |
<%= link_to 'Back', professors_path %>

app/views/professors/index.html.erb
<h1>Listing professors</h1>

<table>
  <tr>
    <th>Professor</th>
    <th>Professor name</th>
    <th>Sector</th>
    <th>Category</th>
    <th>Room</th>
    <th>Building</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @professors.each do |professor| %>
  <tr>
    <td><%= professor.professor_id %></td>
    <td><%= professor.professor_name %></td>
    <td><%= professor.sector %></td>
    <td><%= professor.category %></td>
    <td><%= professor.room %></td>
    <td><%= professor.building %></td>
    <td><%= link_to 'Show', professor %></td>
    <td><%= link_to 'Edit', edit_professor_path(professor) %></td>
    <td><%= link_to 'Destroy', professor, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Professor', new_professor_path %>

app/views/professors/new.html.erb
<h1>New professor</h1>

<%= render 'form' %>

<%= link_to 'Back', professors_path %>

app/views/professors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Professor:</b>
  <%= @professor.professor_id %>
</p>

<p>
  <b>Professor name:</b>
  <%= @professor.professor_name %>
</p>

<p>
  <b>Sector:</b>
  <%= @professor.sector %>
</p>

<p>
  <b>Category:</b>
  <%= @professor.category %>
</p>

<p>
  <b>Room:</b>
  <%= @professor.room %>
</p>

<p>
  <b>Building:</b>
  <%= @professor.building %>
</p>


<%= link_to 'Edit', edit_professor_path(@professor) %> |
<%= link_to 'Back', professors_path %>